apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-pdb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: low-pdb
  template:
    metadata:
      labels:
        app: low-pdb
    spec:
      priorityClassName: low-priority-lab
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"