apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-priority-load
spec:
  replicas: 5
  selector:
    matchLabels:
      app: low-load
  template:
    metadata:
      labels:
        app: low-load
    spec:
      priorityClassName: low-priority-lab
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"