apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy-deployment
  namespace: synergy-lab
  labels:
    app: synergy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergy
  template:
    metadata:
      labels:
        app: synergy
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
      containers:
        - name: synergy-app
          image: busybox:stable
          command:
            - sh
            - -c
            - |
              mkdir -p /var/log
              touch /var/log/synergy-deployment.log
              while true; do
                echo "$(date) : hello from synergy-app" >> /var/log/synergy-deployment.log
                sleep 5
              done
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
        - name: sidecar
          image: busybox:stable
          command:
            - /bin/sh
            - -c
            - tail -n+1 -f /var/log/synergy-deployment.log
          volumeMounts:
            - name: log-volume
              mountPath: /var/log