apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-logger
  namespace: priority
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-logger
  template:
    metadata:
      labels:
        app: busybox-logger
    spec:
      priorityClassName: user-medium
      containers:
      - name: logger
        image: busybox:1.36
        command: ["sh", "-c", "while true; do echo $(date) >> /var/log/busy.log; sleep 5; done"]
        resources:
          requests:
            cpu: "300m"
            memory: "64Mi"
        volumeMounts:
        - name: logs
          mountPath: /var/log
      volumes:
      - name: logs
        emptyDir: {}